# Picked from https://gist.github.com/jonfriesen/1c64bebdd2b30ba1b2465c259f070459
language: go
dist: bionic

go:
  - 1.14.x
  - tip
  - release

git:
    depth: 1

matrix:
    allow_failures:
        - go: tip

    fast_finish: true

install: true

# Check webhook integration    
notifications:
    email: false

before_script:
    - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.27.0
    
script:
    - golangci-lint run
    - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)
