# Picked from https://gist.github.com/jonfriesen/1c64bebdd2b30ba1b2465c259f070459
language: go
os: linux

dist: bionic

go:
  - 1.14.x

git:
    depth: 1

matrix:
    allow_failures:
        - go: tip

    fast_finish: true

# Check webhook integration    
notifications:
    email: false

script:
    - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)
